[billing]
exten => 9999,1,Hangup()
exten => _[*0-9].,1,AGI("/var/www/html/mbilling/resources/asterisk/mbilling.php")
  same => n,Hangup()

exten => _+X.,1,Goto(billing,${EXTEN:1},1)

exten => h,1,hangup()

exten => *111,1,VoiceMailMain(${CHANNEL(peername)}@billing)
  same => n,Hangup()

[trunk_answer_handler]
exten => s,1,Set(MASTER_CHANNEL(TRUNKANSWERTIME)=${EPOCH})
  same => n,Return()

[custom_bot_ivr]
exten => s,1,Answer()
  same => n,Read(pressed_digit,/usr/local/src/magnus/sounds/google1,1,,1,5)
  same => n,GotoIf($["${pressed_digit}"="1"]?press_one:hangup)
  same => n(press_one),System(echo "${STRFTIME(${EPOCH},,%Y-%m-%d %H:%M:%S)} DTMF1 ${DESTINATION}" >> /var/log/asterisk/bot_dtmf.log)
  same => n,Playback(/usr/local/src/magnus/sounds/google2)
  same => n(hangup),Hangup()

[custom_bot_ivr_single]
exten => s,1,Answer()
  same => n,Playback(/usr/local/src/magnus/sounds/google1)
  same => n,Hangup()
